packages:
  - "apps/*"
allowBuilds:
  '@google/genai': true
  koffi: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@josephyoung/pi-heimdall'
onlyBuiltDependencies:
  - "@google/genai"
  - esbuild
  - koffi
  - protobufjs
patchedDependencies:
  '@josephyoung/pi-heimdall@0.2.15': patches/@josephyoung__pi-heimdall@0.2.15.patch
