packages:
  - "apps/*"
patchedDependencies:
  '@casualjim/pi-heimdall@0.2.10': patches/@casualjim__pi-heimdall@0.2.10.patch
allowBuilds:
  '@google/genai': true
  koffi: true
  protobufjs: true
onlyBuiltDependencies:
  - "@google/genai"
  - esbuild
  - koffi
  - protobufjs
