packages:
  - "apps/*"
allowBuilds:
  '@google/genai': true
  koffi: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@josephyoung/pi-heimdall@0.2.12'
onlyBuiltDependencies:
  - "@google/genai"
  - esbuild
  - koffi
  - protobufjs
