"""Classify every flow_spec.py symbol into a split owner. No unknown owners."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "tests" / "fixtures" / "flow_spec_split" / "ast_inventory.json"
OUT = ROOT / "tests" / "fixtures" / "flow_spec_split" / "symbol_owners.json"

# Explicit public / well-known owners. Everything else is classified by name prefix.
EXPLICIT: dict[str, dict[str, str]] = {}

SHARED_MODELS = {
    "ParamField", "SelectBinding", "IdentityBinding", "SystemValue", "FlowStep",
    "FlowLink", "RequestFact", "RequestAnalysis", "RequestUsage", "RequestFacts",
    "CapabilityRequestRef", "CapabilityField", "CapabilityDependency",
    "CapabilityRelation", "ReviewItem", "FlowCapability", "RecordedGoal", "FlowSpec",
}

# FlowSpecConflictError is raised by controlled edits / agent version checks.
EXPLICIT["FlowSpecConflictError"] = {
    "owner": "shared",
    "module": "flow_spec_core.controlled_edits",
    "note": "Conflict error for fingerprint-gated edits",
}

for name in SHARED_MODELS:
    EXPLICIT[name] = {
        "owner": "shared",
        "module": "flow_spec_core.models",
        "note": "Pydantic data model",
    }

EXPLICIT.update({
    "executable_flow_links": {
        "owner": "stage6",
        "module": "capability_contracts",
        "note": "Grounded executable dependency filter",
    },
    "sync_capability_scoped_views": {
        "owner": "stage6",
        "module": "capability_contracts",
        "note": "Capability IO/scoped view sync",
    },
    "sync_flow_spec_models": {
        "owner": "stage5",
        "module": "flow_materialization.builder",
        "note": "Materialized-spec consistency recompute; called from FlowSpec validator",
    },
    "to_flow_spec": {
        "owner": "stage5",
        "module": "flow_materialization.builder",
        "note": "Stage 5 materialization entry",
    },
    "classify_network_request": {
        "owner": "stage2",
        "module": "recording_facts",
        "note": "Request role classification from captured facts",
    },
    "orchestrate_flow_capabilities": {
        "owner": "stage6",
        "module": "capability_contracts",
        "note": "Legacy capability orchestration around compiler",
    },
    "build_review_items": {
        "owner": "stage5",
        "module": "flow_materialization.builder",
        "note": "Review items from materialized contracts",
    },
    "refresh_review_items": {
        "owner": "stage5",
        "module": "flow_materialization.builder",
        "note": "Refresh review items",
    },
    "flow_spec_release_payload": {
        "owner": "shared",
        "module": "flow_spec_core.serialization",
        "note": "Pure dump + drop request_graph; re-exported by flow_release",
    },
    "flow_spec_fingerprint": {
        "owner": "shared",
        "module": "flow_spec_core.fingerprints",
        "note": "Stable executable fingerprint",
    },
    "_execution_fingerprint_payload": {
        "owner": "shared",
        "module": "flow_spec_core.fingerprints",
        "note": "Fingerprint projection",
    },
    "_flow_fingerprint": {
        "owner": "shared",
        "module": "flow_spec_core.fingerprints",
        "note": "Fingerprint hash helper",
    },
    "_FINGERPRINT_NON_EXECUTABLE_KEYS": {
        "owner": "shared",
        "module": "flow_spec_core.fingerprints",
        "note": "Keys stripped from fingerprint payload",
    },
    "_stable_json_hash": {
        "owner": "shared",
        "module": "flow_spec_core.fingerprints",
        "note": "Stable JSON hash",
    },
    "append_flow_version": {
        "owner": "shared",
        "module": "flow_spec_core.versioning",
        "note": "Version bump metadata",
    },
    "ensure_flow_version": {
        "owner": "shared",
        "module": "flow_spec_core.versioning",
        "note": "Ensure first version exists",
    },
    "flow_spec_to_summary": {
        "owner": "shared",
        "module": "flow_client_projection",
        "note": "Lightweight summary projection",
    },
    "flow_spec_to_api_request": {
        "owner": "shared",
        "module": "flow_spec_core.request_contract",
        "note": "Compile executable request contract",
    },
    "compile_capability_to_api_request": {
        "owner": "shared",
        "module": "flow_spec_core.request_contract",
        "note": "Capability-scoped request compilation",
    },
    "capability_to_flow_spec_view": {
        "owner": "stage6",
        "module": "capability_contracts",
        "note": "Capability-scoped FlowSpec view",
    },
    "flow_spec_capability_contracts": {
        "owner": "stage6",
        "module": "capability_contracts",
        "note": "Public capability contract snapshot",
    },
    "dry_run_flow_spec": {
        "owner": "shared",
        "module": "flow_spec_core.request_contract",
        "note": "Pure dry-run of compiled contract",
    },
    "prepare_flow_spec_for_publish": {
        "owner": "stage8",
        "module": "flow_release",
        "note": "Release preparation",
    },
    "prepare_flow_release_candidate": {
        "owner": "stage8",
        "module": "flow_release",
        "note": "Release candidate",
    },
    "validate_flow_spec": {
        "owner": "shared",
        "module": "flow_spec_core.validation",
        "note": "Compatibility composition of structure/materialized/capability/release checks",
    },
    "flow_spec_to_client": {
        "owner": "shared",
        "module": "flow_client_projection",
        "note": "Client-safe projection",
    },
    "apply_flow_edits": {
        "owner": "shared",
        "module": "flow_spec_core.controlled_edits",
        "note": "Generic controlled edit primitive",
    },
    "apply_client_flow_patch": {
        "owner": "shared",
        "module": "flow_spec_core.controlled_edits",
        "note": "Client patch primitive",
    },
    "auto_fix_flow_spec": {
        "owner": "stage6",
        "module": "capability_contracts",
        "note": "Deterministic capability/contract repair edits; not stage 7",
    },
    "recording_agent_state": {
        "owner": "stage3",
        "module": "recording_analysis_state",
        "note": "Read-only recording agent state",
    },
    "recording_agent_validation": {
        "owner": "stage4",
        "module": "recording_agent_contract",
        "note": "Agent submission validation",
    },
    "apply_recording_agent_submission": {
        "owner": "stage4",
        "module": "recording_agent_contract",
        "note": "Agent op application",
    },
    "recording_capability_plan_complete": {
        "owner": "stage4",
        "module": "recording_agent_contract",
        "note": "submission_complete / plan terminal check",
    },
    "render_business_description": {
        "owner": "stage8",
        "module": "flow_client_projection",
        "note": "Human-readable description from spec; no inference",
    },
    "ensure_recorded_goal": {
        "owner": "stage5",
        "module": "flow_materialization.builder",
        "note": "RecordedGoal projection from materialized spec",
    },
    "promote_request_to_step": {
        "owner": "stage5",
        "module": "flow_materialization.request_steps",
        "note": "Promote a request fact to a FlowStep",
    },
    "rebuild_flow_dependencies": {
        "owner": "stage5",
        "module": "flow_materialization.links",
        "note": "Rebuild captured dependency links",
    },
    "flow_spec_user_params": {
        "owner": "shared",
        "module": "flow_spec_core.request_contract",
        "note": "List caller-facing params",
    },
    "flow_spec_required_params": {
        "owner": "shared",
        "module": "flow_spec_core.request_contract",
        "note": "List required caller params",
    },
    "READ_CAPABILITY_KINDS": {
        "owner": "stage6",
        "module": "capability_contracts",
        "note": "Capability kind constant",
    },
    "WRITE_CAPABILITY_KINDS": {
        "owner": "stage6",
        "module": "capability_contracts",
        "note": "Capability kind constant",
    },
    "ALLOWED_CAPABILITY_KINDS": {
        "owner": "stage6",
        "module": "capability_contracts",
        "note": "Capability kind constant",
    },
})

# Name-prefix / substring rules applied in order. First match wins.
PREFIX_RULES: list[tuple[str, str, str]] = [
    # Stage 4 agent protocol
    ("_recording_", "stage4", "recording_agent_contract"),
    ("_RECORDING_", "stage4", "recording_agent_contract"),
    ("_LIVE_PLAN_", "stage4", "recording_agent_contract"),
    ("_validate_recording_agent_ops", "stage4", "recording_agent_contract"),
    ("_live_capability_plan_is_terminal", "stage4", "recording_agent_contract"),
    ("_allowed_values_from_exc", "stage4", "recording_agent_contract"),
    ("_META_ONLY_REPAIR_OPS", "stage4", "recording_agent_contract"),
    # Stage 2 facts
    ("_request_fact", "stage2", "recording_facts"),
    ("_build_request_facts", "stage2", "recording_facts"),
    ("_REQUEST_OBSERVER_KEYS", "stage2", "recording_facts"),
    ("_attach_request_role", "stage2", "recording_facts"),
    ("_option_sources_from_page_enum", "stage2", "recording_facts"),
    ("_api_option_source_refs", "stage2", "recording_facts"),
    ("_page_enum_options_from_request_facts", "stage2", "recording_facts"),
    ("_is_api_like_request_fact", "stage2", "recording_facts"),
    ("_request_analysis_from_entry", "stage2", "recording_facts"),
    ("_request_signature", "stage2", "recording_facts"),
    ("_compact_repeated_endpoint_observations", "stage2", "recording_facts"),
    ("classify_network_request", "stage2", "recording_facts"),
    ("_role_row", "stage2", "recording_facts"),
    ("_is_noise_request", "stage2", "recording_facts"),
    ("_looks_telemetry_request", "stage2", "recording_facts"),
    ("_looks_graphql_request", "stage2", "recording_facts"),
    ("_has_query_action_evidence", "stage2", "recording_facts"),
    ("_request_has_business_query_evidence", "stage2", "recording_facts"),
    ("_request_role_key", "stage2", "recording_facts"),
    ("_request_order_value", "stage2", "recording_facts"),
    ("_request_precedes", "stage2", "recording_facts"),
    ("_dedupe_request_identities", "stage2", "recording_facts"),
    ("_dedupe_preread_candidates", "stage2", "recording_facts"),
    ("_preread_", "stage2", "recording_facts"),
    ("_request_transaction_id", "stage2", "recording_facts"),
    ("_request_has_command_anchor", "stage2", "recording_facts"),
    ("_workflow_context_values_for_request", "stage2", "recording_facts"),
    ("_record_identity_values_for_request", "stage2", "recording_facts"),
    ("_QUERY_ACTION_RE", "stage2", "recording_facts"),
    ("_INTERNAL_WORKFLOW_READ_RE", "stage2", "recording_facts"),
    ("_BUSINESS_QUERY_PATH_RE", "stage2", "recording_facts"),
    ("_TYPEAHEAD_PATH_RE", "stage2", "recording_facts"),
    ("_WORKFLOW_CONTEXT_TOKENS", "stage2", "recording_facts"),
    ("_TRANSPORT_FILTER_KEYS", "stage2", "recording_facts"),
    ("_NOISE_EXTS", "stage2", "recording_facts"),
    ("_NOISE_SEGS", "stage2", "recording_facts"),
    ("_OPTION_SEGS", "stage2", "recording_facts"),
    ("_WRITE_HINT_SEGS", "stage2", "recording_facts"),
    # Field contracts
    ("_apply_create_form_field_contracts", "stage5", "flow_materialization.field_contracts.create_form"),
    ("_apply_edit_form_field_contracts", "stage5", "flow_materialization.field_contracts.edit_form"),
    ("_apply_query_form_field_contracts", "stage5", "flow_materialization.field_contracts.query_form"),
    ("_apply_row_command_field_contracts", "stage5", "flow_materialization.field_contracts.row_command"),
    ("_apply_page_rule_caller_override", "stage5", "flow_materialization.field_contracts.page_rules"),
    ("_apply_date_range_companions", "stage5", "flow_materialization.field_contracts.page_rules"),
    ("_mark_auto_fill_caller_override", "stage5", "flow_materialization.field_contracts.page_rules"),
    ("_infer_arithmetic_computed_fields", "stage5", "flow_materialization.field_contracts.computed"),
    ("_infer_computed_runtime_fields", "stage5", "flow_materialization.field_contracts.computed"),
    ("_infer_selected_option_row_fields", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_apply_mechanical_field_contracts", "stage5", "flow_materialization.builder"),
    ("_apply_successful_omit_optional", "stage5", "flow_materialization.field_contracts.required"),
    ("_param_has_local_required_marker", "stage5", "flow_materialization.field_contracts.required"),
    ("_param_has_page_required_evidence", "stage5", "flow_materialization.field_contracts.required"),
    ("_param_required_agent_classified", "stage5", "flow_materialization.field_contracts.required"),
    # Stage 6 capability helpers
    ("_capability_", "stage6", "capability_contracts"),
    ("_CAPABILITY_", "stage6", "capability_contracts"),
    ("_sync_capability_", "stage6", "capability_contracts"),
    ("_merge_capability_", "stage6", "capability_contracts"),
    ("_normalize_capability_", "stage6", "capability_contracts"),
    ("_prune_empty_capabilities", "stage6", "capability_contracts"),
    ("_prune_auth_materializations", "stage6", "capability_contracts"),
    ("_collapse_duplicate_generated_capabilities", "stage6", "capability_contracts"),
    ("_generated_capability_is_protected", "stage6", "capability_contracts"),
    ("_default_capability_nodes", "stage6", "capability_contracts"),
    ("_ordered_capability_request_refs", "stage6", "capability_contracts"),
    ("_write_contract_is_batch", "stage6", "capability_contracts"),
    ("_semantic_plan_coverage", "stage6", "capability_contracts"),
    ("_sync_capability_io_schemas", "stage6", "capability_contracts"),
    ("_apply_semantic_business_understanding", "stage6", "capability_contracts"),
    ("_complete_semantic_plan_from_spec", "stage6", "capability_contracts"),
    ("_semantic_candidate_gate", "stage6", "capability_contracts"),
    ("_semantic_mutable_context", "stage6", "capability_contracts"),
    ("_semantic_wire_hash", "stage6", "capability_contracts"),
    ("_auto_confirm_ready_capabilities", "stage6", "capability_contracts"),
    ("_auto_fix_target_capability", "stage6", "capability_contracts"),
    ("_deterministic_capability_repair_edits", "stage6", "capability_contracts"),
    ("_autofix_ops_to_edits", "stage6", "capability_contracts"),
    ("_flow_autofix_context", "stage6", "capability_contracts"),
    ("_planner_patch_edits", "stage6", "capability_contracts"),
    ("_select_flow_capability", "stage6", "capability_contracts"),
    ("_transition_capability_kind", "stage6", "capability_contracts"),
    ("_find_capability_", "stage6", "capability_contracts"),
    ("_invalidate_capabilit", "stage6", "capability_contracts"),
    ("_canonicalize_public_capability_identities", "stage6", "capability_contracts"),
    ("_normalize_generated_capability_semantics", "stage6", "capability_contracts"),
    ("_repair_generated_capability_contracts", "stage6", "capability_contracts"),
    ("_ensure_capability_explanations", "stage6", "capability_contracts"),
    ("_generalize_capability_title", "stage6", "capability_contracts"),
    ("_page_context_business_name", "stage6", "capability_contracts"),
    ("_active_capability_step_ids", "stage6", "capability_contracts"),
    ("_remove_capability_step_nodes", "stage6", "capability_contracts"),
    ("_reorder_capability_call_nodes", "stage6", "capability_contracts"),
    ("_iter_capability_nodes", "stage6", "capability_contracts"),
    ("_batch_capability_input_schema", "stage6", "capability_contracts"),
    ("_disambiguate_capability_param_keys", "stage6", "capability_contracts"),
    ("READ_CAPABILITY_KINDS", "stage6", "capability_contracts"),
    ("WRITE_CAPABILITY_KINDS", "stage6", "capability_contracts"),
    ("ALLOWED_CAPABILITY_KINDS", "stage6", "capability_contracts"),
    ("_WRITE_METHODS", "stage6", "capability_contracts"),
    ("_PUBLIC_ROLE_BY_INTERNAL", "stage6", "capability_contracts"),
    ("_PUBLIC_SOURCE_BY_INTERNAL", "stage6", "capability_contracts"),
    ("_FIELD_MAPPED_CAPABILITY_RELATIONS", "stage6", "capability_contracts"),
    ("_GENERIC_CAPABILITY_INTENT_RE", "stage6", "capability_contracts"),
    ("_GENERIC_PAGE_TITLE_RE", "stage6", "capability_contracts"),
    ("_ACTION_LABELS", "stage6", "capability_contracts"),
    ("_INSTANCE_TITLE_SUFFIX_RE", "stage6", "capability_contracts"),
    ("_MUTATING_RECORD_KINDS", "stage6", "capability_contracts"),
    ("_only_grounded_screenshot_query_params_added", "stage6", "capability_contracts"),
    # Stage 8 / client
    ("_client_", "shared", "flow_client_projection"),
    ("_CLIENT_", "shared", "flow_client_projection"),
    ("_public_source_kind", "shared", "flow_client_projection"),
    ("_public_request_role", "shared", "flow_client_projection"),
    ("_client_response_projection", "shared", "flow_client_projection"),
    # Publish / release helpers used by validate_flow_spec composition
    ("_diagnostic_publish_findings", "stage8", "flow_release"),
    ("_publish_issue_groups", "stage8", "flow_release"),
    ("_field_source_review_issues", "stage8", "flow_release"),
    ("_enum_mapping_issues", "stage8", "flow_release"),
    ("_compiled_contract_issue_groups", "stage8", "flow_release"),
    ("_compiled_contract_review_items", "stage8", "flow_release"),
    ("_generated_review_items", "stage8", "flow_release"),
    ("_PUBLISH_BLOCKING_REVIEW_TYPES", "stage8", "flow_release"),
    ("_legacy_fact_check_is_grounded", "stage8", "flow_release"),
    ("_executor_fact_check_is_verified", "stage8", "flow_release"),
    ("_prune_invalid_fact_checks", "stage8", "flow_release"),
    ("_runtime_param_publish_error", "stage8", "flow_release"),
    ("_manual_enum_mapping_complete", "stage8", "flow_release"),
    ("_incomplete_page_enum_is_executable", "stage8", "flow_release"),
    ("_enum_map_covers_recorded_value", "stage8", "flow_release"),
    ("_enum_options_look_value_only", "stage8", "flow_release"),
    ("_select_has_executable_options", "stage8", "flow_release"),
    ("_param_looks_exposed_internal_value", "stage8", "flow_release"),
    ("_VALUE_ONLY_LABEL_RE", "stage8", "flow_release"),
    ("_INTERNAL_EXPOSED_PATH_RE", "stage8", "flow_release"),
    # Request contract compilation
    ("_flow_step_to_api_step", "shared", "flow_spec_core.request_contract"),
    ("_param_recorded_value", "shared", "flow_spec_core.request_contract"),
    ("_body_relative_path", "shared", "flow_spec_core.request_contract"),
    ("_step_body_params", "shared", "flow_spec_core.request_contract"),
    ("_ensure_step_body_source", "shared", "flow_spec_core.request_contract"),
    ("ensure_recorded_body_source", "shared", "flow_spec_core.request_contract"),
    ("_flow_step_query_template", "shared", "flow_spec_core.request_contract"),
    ("_flow_step_url_template", "shared", "flow_spec_core.request_contract"),
    ("_api_params", "shared", "flow_spec_core.request_contract"),
    ("_api_sample_inputs", "shared", "flow_spec_core.request_contract"),
    ("_dry_", "shared", "flow_spec_core.request_contract"),
    ("_fact_check_report", "shared", "flow_spec_core.request_contract"),
    ("_select_param_for_runtime", "shared", "flow_spec_core.request_contract"),
    ("_select_binding_is_runtime_executable", "shared", "flow_spec_core.request_contract"),
    ("_runtime_select_bindings", "shared", "flow_spec_core.request_contract"),
    ("_step_runtime_identity", "shared", "flow_spec_core.request_contract"),
    ("_executable_identity_source", "shared", "flow_spec_core.request_contract"),
    ("_step_samples", "shared", "flow_spec_core.request_contract"),
    ("_step_param_map", "shared", "flow_spec_core.request_contract"),
    ("_step_wire_formats", "shared", "flow_spec_core.request_contract"),
    ("_clean_path_prefix", "shared", "flow_spec_core.normalization"),
    ("_apply_grounded_indexed_range_names", "stage5", "flow_materialization.field_contracts.common"),
    # Controlled edits
    ("_PARAM_ALLOWED_FIELDS", "shared", "flow_spec_core.controlled_edits"),
    ("_STEP_ALLOWED_FIELDS", "shared", "flow_spec_core.controlled_edits"),
    ("_CAPABILITY_ALLOWED_FIELDS", "shared", "flow_spec_core.controlled_edits"),
    ("_CLIENT_SERVER_OWNED_STEP_FIELDS", "shared", "flow_spec_core.controlled_edits"),
    ("_CLIENT_SELECT_EDIT_FIELDS", "shared", "flow_spec_core.controlled_edits"),
    ("_CLIENT_SOURCE_KINDS", "shared", "flow_spec_core.controlled_edits"),
    ("_INTERNAL_SOURCE_CONTRACT", "shared", "flow_spec_core.controlled_edits"),
    ("_AUTOMATED_FIELD_EDIT_ACTORS", "shared", "flow_spec_core.controlled_edits"),
    ("_client_select_patch", "shared", "flow_spec_core.controlled_edits"),
    ("_client_source_patch", "shared", "flow_spec_core.controlled_edits"),
    ("_find_step", "shared", "flow_spec_core.controlled_edits"),
    ("_find_param", "shared", "flow_spec_core.controlled_edits"),
    ("_find_link", "shared", "flow_spec_core.controlled_edits"),
    ("_resolve_param_reference", "shared", "flow_spec_core.controlled_edits"),
    ("_reference_targets_param", "shared", "flow_spec_core.controlled_edits"),
    ("_validate_link_endpoint", "shared", "flow_spec_core.controlled_edits"),
    ("_ensure_unique_link", "shared", "flow_spec_core.controlled_edits"),
    ("_matching_link", "shared", "flow_spec_core.controlled_edits"),
    ("_merge_link", "shared", "flow_spec_core.controlled_edits"),
    ("_remove_step", "shared", "flow_spec_core.controlled_edits"),
    ("_remove_param_incoming_links", "shared", "flow_spec_core.controlled_edits"),
    ("_record_param_manual_contract", "shared", "flow_spec_core.controlled_edits"),
    ("_reset_param_source", "shared", "flow_spec_core.controlled_edits"),
    ("_transition_param_type", "shared", "flow_spec_core.controlled_edits"),
    ("_apply_link_sources", "shared", "flow_spec_core.controlled_edits"),
    ("_apply_user_link_source", "shared", "flow_spec_core.controlled_edits"),
    ("_apply_capability_field_to_param", "stage6", "capability_contracts"),
    ("_rename_param_public_key", "shared", "flow_spec_core.controlled_edits"),
    ("_hydrate_select_source_contract", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_bind_option_source", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_set_capability_loop_source", "stage6", "capability_contracts"),
    ("_set_capability_return", "stage6", "capability_contracts"),
    ("_upsert_capability_", "stage6", "capability_contracts"),
    ("_upsert_global_link_from_capability_dependency", "stage6", "capability_contracts"),
    # Description rendering
    ("_description_", "stage8", "flow_client_projection"),
    ("_derive_step_name", "stage5", "flow_materialization.titles"),
    ("_looks_internal", "shared", "flow_spec_core.normalization"),
    ("_unique_params", "stage8", "flow_client_projection"),
    ("_semantic_purpose", "stage8", "flow_client_projection"),
    ("_default_purpose", "stage8", "flow_client_projection"),
    # Review items
    ("_review_", "stage5", "flow_materialization.builder"),
    ("_severity_rank", "stage5", "flow_materialization.builder"),
    ("_param_dedupe_key", "stage5", "flow_materialization.request_steps"),
    ("_enum_sources_compatible", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_refresh_param_enum_description", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_merge_enum_values", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_param_quality", "stage5", "flow_materialization.request_steps"),
    ("_dedupe_step_params", "stage5", "flow_materialization.request_steps"),
    ("_flow_path_", "shared", "flow_spec_core.normalization"),
    ("_FLOW_PATH_MISSING", "shared", "flow_spec_core.normalization"),
    # Step build / usage / links / hydration / response maps
    ("_build_step_from_capture", "stage5", "flow_materialization.request_steps"),
    ("_params_from_get_query", "stage5", "flow_materialization.request_steps"),
    ("_params_from_url_path", "stage5", "flow_materialization.request_steps"),
    ("_query_param_type", "stage5", "flow_materialization.request_steps"),
    ("_request_query_values", "stage5", "flow_materialization.request_steps"),
    ("_request_url_with_query", "stage5", "flow_materialization.request_steps"),
    ("_detect_query_selects", "stage5", "flow_materialization.request_steps"),
    ("_detect_composite_entity_selects", "stage5", "flow_materialization.request_steps"),
    ("_mark_request_materialized", "stage5", "flow_materialization.request_usage"),
    ("_canonicalize_materialized_request_identities", "stage5", "flow_materialization.request_usage"),
    ("_upgrade_materialized_query_facts", "stage5", "flow_materialization.request_usage"),
    ("_add_request_step_from_fact", "stage5", "flow_materialization.request_steps"),
    ("_insert_promoted_step", "stage5", "flow_materialization.request_steps"),
    ("_step_dedupe_key", "stage5", "flow_materialization.request_steps"),
    ("_is_dedupable_read_step", "stage5", "flow_materialization.request_steps"),
    ("_dedupe_flow_steps", "stage5", "flow_materialization.request_steps"),
    ("_append_query_params_to_step", "stage5", "flow_materialization.request_steps"),
    ("_param_type_from_value", "stage5", "flow_materialization.request_steps"),
    ("_default_step_name", "stage5", "flow_materialization.titles"),
    ("_select_name_for_step", "stage5", "flow_materialization.titles"),
    ("_derive_title", "stage5", "flow_materialization.titles"),
    ("_infer_type_from_value", "shared", "flow_spec_core.normalization"),
    ("_path_from_url", "shared", "flow_spec_core.normalization"),
    ("_norm_field_name", "shared", "flow_spec_core.normalization"),
    ("_merge_flow_read_sources", "stage5", "flow_materialization.links"),
    ("_discover_record_hydration_links", "stage5", "flow_materialization.hydration"),
    ("_latest_response_key_map_candidates", "stage5", "flow_materialization.response_maps"),
    ("_materialize_captured_response_key_maps", "stage5", "flow_materialization.response_maps"),
    ("_enrich_materialized_response_shapes", "stage5", "flow_materialization.response_maps"),
    ("_response_shape_evidence_score", "stage5", "flow_materialization.response_maps"),
    ("_response_list_paths", "stage5", "flow_materialization.response_maps"),
    ("_link_is_auto_generated", "stage5", "flow_materialization.links"),
    ("_auto_dependency_", "stage5", "flow_materialization.links"),
    ("_auto_link_has_grounded_contract", "stage5", "flow_materialization.links"),
    ("_prune_unsafe_auto_links", "stage5", "flow_materialization.links"),
    ("_flow_link_kind", "stage5", "flow_materialization.links"),
    ("_sync_link_sources", "stage5", "flow_materialization.links"),
    ("_dependency_", "stage5", "flow_materialization.links"),
    ("_useful_link_value", "stage5", "flow_materialization.links"),
    ("_response_referenced_later", "stage5", "flow_materialization.links"),
    ("_sample_hit_count", "stage5", "flow_materialization.links"),
    ("_trace_pos", "stage5", "flow_materialization.links"),
    ("_BORING_LINK_VALUES", "stage5", "flow_materialization.links"),
    ("rebuild_flow_dependencies", "stage5", "flow_materialization.links"),
    ("_record_rejected_dependency", "stage5", "flow_materialization.links"),
    ("_rejected_dependency_sigs", "stage5", "flow_materialization.links"),
    ("_skip_auto_dependency_target", "stage5", "flow_materialization.links"),
    ("_request_sequence_value", "stage5", "flow_materialization.request_steps"),
    ("_step_sequence", "stage5", "flow_materialization.request_steps"),
    ("_entry_sequence", "stage5", "flow_materialization.request_steps"),
    ("_samples_for_captured_request", "stage5", "flow_materialization.request_steps"),
    ("_merge_duplicate_step_contract", "stage5", "flow_materialization.request_steps"),
    ("_retarget_step_references", "stage5", "flow_materialization.request_usage"),
    ("_param_contract_richness", "stage5", "flow_materialization.request_steps"),
    ("_step_contract_richness", "stage5", "flow_materialization.request_steps"),
    ("_infer_wire_format", "stage5", "flow_materialization.request_steps"),
    ("_rebind_saved_field_evidence", "stage5", "flow_materialization.builder"),
    ("_ground_saved_page_enums", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_audit_step_param_contracts", "stage5", "flow_materialization.field_contracts.common"),
    ("_sync_step_option_contracts", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_repair_readonly_control_defaults", "stage5", "flow_materialization.field_contracts.edit_form"),
    ("_repair_uncontrolled_write_state_fields", "stage5", "flow_materialization.field_contracts.create_form"),
    ("_repair_structural_option_bindings", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_refresh_api_option_display_labels", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_attach_option_source_memberships", "stage6", "capability_contracts"),
    ("_option_binding_", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_weak_automatic_text_option_binding", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_looks_quantitative_option_target", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_find_select_binding", "stage5", "flow_materialization.field_contracts.option_projection"),
    # Field contract common / axes
    ("_field_leaf_token", "stage5", "flow_materialization.field_contracts.common"),
    ("_param_group_prefix", "stage5", "flow_materialization.field_contracts.common"),
    ("_param_control_kinds", "stage5", "flow_materialization.field_contracts.common"),
    ("_param_has_page_control_evidence", "stage5", "flow_materialization.field_contracts.common"),
    ("_param_control_is_readonly", "stage5", "flow_materialization.field_contracts.common"),
    ("_param_has_manual_contract", "stage5", "flow_materialization.field_contracts.common"),
    ("_param_field_manually_edited", "stage5", "flow_materialization.field_contracts.common"),
    ("_param_axis_manually_edited", "stage5", "flow_materialization.field_contracts.common"),
    ("_param_has_full_lock", "stage5", "flow_materialization.field_contracts.common"),
    ("_param_source_agent_classified", "stage5", "flow_materialization.field_contracts.common"),
    ("_looks_pagination_field", "stage5", "flow_materialization.field_contracts.common"),
    ("_looks_audit_system_leaf", "stage5", "flow_materialization.field_contracts.common"),
    ("_looks_current_user_field", "stage5", "flow_materialization.field_contracts.common"),
    ("_looks_runtime_field", "stage5", "flow_materialization.field_contracts.common"),
    ("_looks_session_specific_value", "stage5", "flow_materialization.field_contracts.common"),
    ("_looks_session_literal_after_key_check", "stage5", "flow_materialization.field_contracts.common"),
    ("_looks_token_field", "stage5", "flow_materialization.field_contracts.common"),
    ("_looks_system_const_field", "stage5", "flow_materialization.field_contracts.common"),
    ("_looks_page_context_field", "stage5", "flow_materialization.field_contracts.common"),
    ("_looks_user_entered_business_field", "stage5", "flow_materialization.field_contracts.common"),
    ("_looks_display_echo_field", "stage5", "flow_materialization.field_contracts.edit_form"),
    ("_CURRENT_USER_LEAVES", "stage5", "flow_materialization.field_contracts.common"),
    ("_SESSION_LITERAL_RE", "stage5", "flow_materialization.field_contracts.common"),
    ("_UUID_LITERAL_RE", "stage5", "flow_materialization.field_contracts.common"),
    ("_PAGE_CONTEXT_LEAVES", "stage5", "flow_materialization.field_contracts.common"),
    ("_RECORD_IDENTITY_LEAVES", "stage5", "flow_materialization.field_contracts.record_identity"),
    ("_is_document_record_identity_path", "stage5", "flow_materialization.field_contracts.record_identity"),
    ("_record_identity_is_caller_owned", "stage5", "flow_materialization.field_contracts.record_identity"),
    ("_param_is_document_record_identity", "stage5", "flow_materialization.field_contracts.record_identity"),
    ("_step_has_stable_record_identity", "stage5", "flow_materialization.field_contracts.record_identity"),
    ("_looks_row_identity_leaf", "stage5", "flow_materialization.field_contracts.record_identity"),
    ("_param_exposed_to_caller", "stage5", "flow_materialization.field_contracts.caller_ownership"),
    ("_param_requires_caller_input", "stage5", "flow_materialization.field_contracts.caller_ownership"),
    ("_param_was_caller_typed", "stage5", "flow_materialization.field_contracts.caller_ownership"),
    ("_param_has_editable_control_evidence", "stage5", "flow_materialization.field_contracts.caller_ownership"),
    ("_field_has_unlocked_editable_control", "stage5", "flow_materialization.field_contracts.caller_ownership"),
    ("_external_capability_input", "stage5", "flow_materialization.field_contracts.caller_ownership"),
    ("_param_source_guess", "stage5", "flow_materialization.field_contracts.common"),
    ("_header_value_matches_token", "stage5", "flow_materialization.field_contracts.common"),
    ("_request_header_source_for_token", "stage5", "flow_materialization.field_contracts.common"),
    ("_sample_value_set", "shared", "flow_spec_core.normalization"),
    ("_is_missing_wire_placeholder", "stage5", "flow_materialization.field_contracts.common"),
    ("_MISSING_WIRE_PLACEHOLDERS", "stage5", "flow_materialization.field_contracts.common"),
    ("_recorded_param_sample", "stage5", "flow_materialization.request_steps"),
    ("_param_has_option_control_evidence", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_param_has_interacted_temporal_control", "stage5", "flow_materialization.field_contracts.common"),
    ("_semantic_recorded_type", "stage5", "flow_materialization.field_contracts.common"),
    ("_canonical_screenshot_control", "stage5", "flow_materialization.field_contracts.common"),
    ("_screenshot_control_", "stage5", "flow_materialization.field_contracts.common"),
    ("_SCREENSHOT_", "stage5", "flow_materialization.field_contracts.common"),
    ("_grounded_control_evidence", "stage5", "flow_materialization.field_contracts.common"),
    ("_grounded_screenshot_query_path", "stage5", "flow_materialization.field_contracts.common"),
    ("_param_has_grounded_", "stage5", "flow_materialization.field_contracts.common"),
    ("_param_has_executable_source", "stage5", "flow_materialization.field_contracts.common"),
    ("_field_source_configuration_advice", "stage5", "flow_materialization.field_contracts.common"),
    ("_query_key_from_param", "stage5", "flow_materialization.request_steps"),
    ("_strip_body_prefix", "shared", "flow_spec_core.normalization"),
    ("_flow_path_assign", "shared", "flow_spec_core.normalization"),
    ("_param_has_grounded_public_name", "stage5", "flow_materialization.field_contracts.common"),
    ("_param_has_grounded_type", "stage5", "flow_materialization.field_contracts.common"),
    # Option projection
    ("_OPTION_SOURCE_KINDS", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_ENUM_PARAM_TYPES", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_ENUM_SOURCE_KINDS", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_OPTION_DESCRIPTION_PREFIXES", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_BORING_COMPOSITE_VALUES", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_is_option_source_url", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_list_payload_has_reference_contract", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_choice_control_triggered", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_read_is_entity_enrichment_lookup", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_read_is_option_source", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_read_transport_can_supply_options", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_read_is_business_entity_collection", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_option_candidate_reads", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_option_source_contract_endpoint", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_select_source_kind", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_select_source_reason", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_enum_options_for_param", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_enum_value_map_for_param", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_enum_label_value", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_explicit_enum_value_map", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_enum_options_description", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_append_reason_detail", "stage5", "flow_materialization.field_contracts.common"),
    ("_upsert_option_description", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_strip_option_descriptions", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_enum_option_map_from_options", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_recorded_scalar_values_match", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_composite_values_match", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_projection_", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_best_option_projection_path", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_attach_select_field_projections", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_page_enum_options_for_request", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_page_enum_contract_for_param", "stage5", "flow_materialization.field_contracts.option_projection"),
    ("_recording_evidence_matches_request", "stage2", "recording_facts"),
    ("_field_evidence_for_request", "stage2", "recording_facts"),
    ("_recording_evidence_matches_scope", "stage2", "recording_facts"),
    ("_list_payload_is_business_records", "stage2", "recording_facts"),
    ("_list_payload_has_conventional_option_contract", "stage2", "recording_facts"),
    ("_request_has_option_endpoint_hint", "stage2", "recording_facts"),
    ("_request_has_reference_entity_hint", "stage2", "recording_facts"),
    ("_response_has_scalar_business_value", "stage2", "recording_facts"),
    ("_request_path", "stage2", "recording_facts"),
    ("_request_segments", "stage2", "recording_facts"),
    ("_request_has_write_hint", "stage2", "recording_facts"),
    ("_request_values", "stage2", "recording_facts"),
    ("_response_values", "stage2", "recording_facts"),
    ("_caller_filter_key", "stage5", "flow_materialization.field_contracts.query_form"),
    ("_business_filter_count", "stage5", "flow_materialization.field_contracts.query_form"),
    # Computed
    ("_ARITHMETIC_STRATEGIES", "stage5", "flow_materialization.field_contracts.computed"),
    ("_IDENTITY_ARITHMETIC_EPS", "stage5", "flow_materialization.field_contracts.computed"),
    ("_INPUT_OPERAND_KINDS", "stage5", "flow_materialization.field_contracts.computed"),
    ("_STABLE_OPERAND_KINDS", "stage5", "flow_materialization.field_contracts.computed"),
    ("_COMPUTED_DATE_STRATEGIES", "stage5", "flow_materialization.field_contracts.computed"),
    ("_COMPUTED_ARITHMETIC_STRATEGIES", "stage5", "flow_materialization.field_contracts.computed"),
    ("_looks_non_quantity_formula_leaf", "stage5", "flow_materialization.field_contracts.computed"),
    ("_looks_count_formula_leaf", "stage5", "flow_materialization.field_contracts.computed"),
    ("_looks_total_formula_leaf", "stage5", "flow_materialization.field_contracts.computed"),
    ("_looks_unit_price_formula_leaf", "stage5", "flow_materialization.field_contracts.computed"),
    ("_looks_percent_formula_leaf", "stage5", "flow_materialization.field_contracts.computed"),
    ("_param_is_quantity_or_formula_leaf", "stage5", "flow_materialization.field_contracts.computed"),
    ("_is_numeric_formula_operand", "stage5", "flow_materialization.field_contracts.computed"),
    ("_is_stable_operand", "stage5", "flow_materialization.field_contracts.computed"),
    ("_arithmetic_", "stage5", "flow_materialization.field_contracts.computed"),
    ("_operand_quality", "stage5", "flow_materialization.field_contracts.computed"),
    ("_identity_product_allowed", "stage5", "flow_materialization.field_contracts.computed"),
    ("_pick_arithmetic_match", "stage5", "flow_materialization.field_contracts.computed"),
    ("_computed_formula_is_complete", "stage5", "flow_materialization.field_contracts.computed"),
    ("_param_is_temporal", "stage5", "flow_materialization.field_contracts.computed"),
    ("_timestamp_is_near_request", "stage5", "flow_materialization.field_contracts.computed"),
    ("_date_like_epoch_seconds", "stage5", "flow_materialization.field_contracts.computed"),
    ("_as_finite_number", "stage5", "flow_materialization.field_contracts.computed"),
    ("_numbers_match", "stage5", "flow_materialization.field_contracts.computed"),
    ("_calendar_date_text", "stage5", "flow_materialization.field_contracts.page_rules"),
    ("_query_range_index", "stage5", "flow_materialization.field_contracts.page_rules"),
    # Create / edit / query / row
    ("_step_is_create_or_submit_form", "stage5", "flow_materialization.field_contracts.create_form"),
    ("_create_form_field_is_system_owned", "stage5", "flow_materialization.field_contracts.create_form"),
    ("_create_unknown_has_caller_evidence", "stage5", "flow_materialization.field_contracts.create_form"),
    ("_mark_create_form_caller_input", "stage5", "flow_materialization.field_contracts.create_form"),
    ("_step_is_record_edit_form", "stage5", "flow_materialization.field_contracts.edit_form"),
    ("_mark_system_hydrated_field", "stage5", "flow_materialization.field_contracts.edit_form"),
    ("_looks_catalog_attribute_leaf", "stage5", "flow_materialization.field_contracts.edit_form"),
    ("_param_has_command_local_control", "stage5", "flow_materialization.field_contracts.row_command"),
    ("_step_is_row_command", "stage5", "flow_materialization.field_contracts.row_command"),
    ("_step_role", "stage5", "flow_materialization.request_steps"),
    ("_step_is_option_read", "stage5", "flow_materialization.field_contracts.query_form"),
    ("_step_is_record_detail_query", "stage5", "flow_materialization.field_contracts.query_form"),
    ("_step_is_business_list_query", "stage5", "flow_materialization.field_contracts.query_form"),
    ("_mark_query_filter_caller", "stage5", "flow_materialization.field_contracts.query_form"),
    ("_request_present_leaves", "stage5", "flow_materialization.field_contracts.required"),
    ("_successful_peer_omitted_leaves", "stage5", "flow_materialization.field_contracts.required"),
    ("_option_row_match_count", "stage5", "flow_materialization.field_contracts.option_projection"),
    # Schema helpers used by capability IO (stage 6) and materialization
    ("_schema_for_param_type", "stage6", "capability_contracts"),
    ("_business_type_for_param", "stage6", "capability_contracts"),
    ("_previous_response_source_step_id", "stage5", "flow_materialization.links"),
    ("_schema_default_for_param", "stage6", "capability_contracts"),
    ("_apply_param_schema_default", "stage6", "capability_contracts"),
    ("_NO_SCHEMA_DEFAULT", "stage6", "capability_contracts"),
    ("_RUNTIME_SUPPLIED_SOURCE_KINDS", "stage5", "flow_materialization.field_contracts.caller_ownership"),
    ("_merge_response_schemas", "stage6", "capability_contracts"),
    ("_schema_from_response_value", "stage6", "capability_contracts"),
    ("_identifier_role_for_field", "stage6", "capability_contracts"),
    ("_IDENTIFIER_ROLE_BY_FIELD", "stage6", "capability_contracts"),
    ("_IDENTIFIER_ROLE_TITLE", "stage6", "capability_contracts"),
    ("_IDENTIFIER_RELATION_TARGET_KINDS", "stage6", "capability_contracts"),
    ("_output_field_is_transport_only", "stage6", "capability_contracts"),
    ("_schema_node_at_path", "stage6", "capability_contracts"),
    ("_apply_output_presentation_evidence", "stage6", "capability_contracts"),
    ("_recorded_goal_from_parts", "stage5", "flow_materialization.builder"),
    ("_recorded_user_param_names", "stage5", "flow_materialization.builder"),
    ("_DEFAULT_RECORDED_FORBIDDEN_ACTIONS", "stage5", "flow_materialization.builder"),
    ("_LEGACY_RECORDED_FORBIDDEN_ACTIONS", "stage5", "flow_materialization.builder"),
    ("_param_path_leaf", "stage6", "capability_contracts"),
    ("_params_can_share_caller_key", "stage6", "capability_contracts"),
    ("_ACTIONABLE_PLACEHOLDER_NAME_RE", "stage6", "capability_contracts"),
    ("_find_request_fact_item", "stage2", "recording_facts"),
    ("_step_request_fact_for_capability", "stage6", "capability_contracts"),
    ("_is_identity_arithmetic", "stage5", "flow_materialization.field_contracts.computed"),
    ("_normalize_actionable_placeholder_param_names", "stage6", "capability_contracts"),
    ("_annotate_identifier_sources", "stage6", "capability_contracts"),
    ("_target_input_values", "stage6", "capability_contracts"),
    ("_identifier_value_is_grounding_evidence", "stage6", "capability_contracts"),
    ("_ground_recorded_identifier_relations", "stage6", "capability_contracts"),
    ("_expand_response_key_map_inputs", "stage6", "capability_contracts"),
    ("_sanitize_capability_nodes", "stage6", "capability_contracts"),
    ("_step_evidence", "stage6", "capability_contracts"),
    ("_is_write_step", "stage6", "capability_contracts"),
    ("_looks_batch_step", "stage6", "capability_contracts"),
    ("_title_without_step_suffix", "stage6", "capability_contracts"),
    ("_query_output_mappings", "stage6", "capability_contracts"),
    ("_flow_capability_id", "stage6", "capability_contracts"),
    ("_stable_capability_id", "stage6", "capability_contracts"),
    ("_repeated_write_command_signature", "stage6", "capability_contracts"),
    ("_write_command_discriminators", "stage6", "capability_contracts"),
    ("_mark_repeated_write_observations", "stage6", "capability_contracts"),
    ("_write_steps", "stage6", "capability_contracts"),
    ("_option_source_step_ids", "stage6", "capability_contracts"),
    ("_business_query_evidence_score", "stage6", "capability_contracts"),
    ("_is_business_query_step", "stage6", "capability_contracts"),
    ("_read_status_steps", "stage6", "capability_contracts"),
    ("_ordered_steps_by_ids", "stage6", "capability_contracts"),
    ("_submit_capability_steps", "stage6", "capability_contracts"),
    ("_schema_path_exists", "stage6", "capability_contracts"),
    ("_add_step_id_to_capability", "stage6", "capability_contracts"),
    ("_set_capability_request_membership", "stage6", "capability_contracts"),
    ("_query_operation_key", "stage6", "capability_contracts"),
    ("_response_identity_match_count", "stage6", "capability_contracts"),
    ("_primary_read_operation_step", "stage6", "capability_contracts"),
    ("_grounded_read_operation_steps", "stage6", "capability_contracts"),
    ("_write_operation_key", "stage6", "capability_contracts"),
    ("_ensure_external_transform_relations", "stage6", "capability_contracts"),
    ("_step_page_id_from_facts", "stage6", "capability_contracts"),
    ("_model_visible_request_facts", "stage3", "recording_analysis_state"),
    ("_semantic_fact_snapshot", "stage4", "recording_agent_contract"),
    ("_semantic_fact_hash", "stage4", "recording_agent_contract"),
    ("_orchestration_context", "stage6", "capability_contracts"),
    ("_retired_capability_step_ids", "stage6", "capability_contracts"),
    ("_removed_capability_names", "stage6", "capability_contracts"),
    ("_remember_removed_capability", "stage6", "capability_contracts"),
    ("_forget_removed_capability", "stage6", "capability_contracts"),
    ("_remember_removed_capability_step", "stage6", "capability_contracts"),
    ("_forget_removed_capability_step", "stage6", "capability_contracts"),
    ("_planned_capability_has_public_anchor", "stage6", "capability_contracts"),
    ("_pre_materialization_semantic_plan_coverage", "stage6", "capability_contracts"),
    ("_public_capability_anchor_step_ids", "stage6", "capability_contracts"),
    ("_is_technical_business_title", "stage6", "capability_contracts"),
    ("_clean_page_business_candidate", "stage6", "capability_contracts"),
    ("_locator_action_name", "stage6", "capability_contracts"),
    ("_step_request_key", "stage6", "capability_contracts"),
    ("_step_request_signature_key", "stage6", "capability_contracts"),
    ("_eligible_business_write_fact", "stage6", "capability_contracts"),
    ("_materialized_step_id_for_request", "stage5", "flow_materialization.request_usage"),
    ("_step_body_is_array", "stage6", "capability_contracts"),
    ("_same_capability_computed_field", "stage6", "capability_contracts"),
    ("_ROUTING_FIELD_RE", "stage6", "capability_contracts"),
    ("_WRITE_COMMAND_DISCRIMINATOR_RE", "stage6", "capability_contracts"),
    ("_CAPABILITY_PATH_PREFIXES", "stage6", "capability_contracts"),
    ("_canonical_step_summary", "stage6", "capability_contracts"),
]


def classify(name: str) -> dict[str, str] | None:
    if name in EXPLICIT:
        return dict(EXPLICIT[name])
    for prefix, owner, module in PREFIX_RULES:
        if name == prefix or name.startswith(prefix):
            return {"owner": owner, "module": module, "note": f"classified by prefix {prefix}"}
    return None


def main() -> None:
    inv = json.loads(INVENTORY.read_text(encoding="utf-8"))
    symbols: dict[str, dict] = {}
    missing: list[str] = []
    for kind, items in (("class", inv["classes"]), ("function", inv["functions"]), ("constant", inv["assigns"])):
        for item in items:
            name = item["name"]
            owner = classify(name)
            if owner is None:
                missing.append(f"{name}@{item['lineno']}")
                continue
            key = name
            # duplicate function names exist (_projection_path_score defined twice)
            if key in symbols:
                key = f"{name}@{item['lineno']}"
                owner["note"] = owner.get("note", "") + f"; duplicate at line {item['lineno']}"
            symbols[key] = {
                "kind": kind,
                "name": name,
                "lineno": item["lineno"],
                "end": item.get("end"),
                "lines": item.get("lines"),
                **owner,
            }
    if missing:
        print("unclassified", len(missing))
        for name in missing:
            print(name)
        raise SystemExit(1)
    owners = {}
    for row in symbols.values():
        owners.setdefault(row["owner"], 0)
        owners[row["owner"]] += 1
    payload = {
        "baseline_head": "7e6f15097cb1704dbedd87df5ca64de0403103ec",
        "source_lines": inv["lines"],
        "source_bytes": inv["bytes"],
        "counts": {
            "class": inv["class_count"],
            "function": inv["function_count"],
            "constant": inv["assign_count"],
            "by_owner": owners,
        },
        "symbols": symbols,
    }
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print("owners", json.dumps(owners, indent=2))
    print("wrote", OUT, "symbols", len(symbols))


if __name__ == "__main__":
    main()
